### ISSUE TITLE
AI Assistant Backend Setup: Base Architecture and CoTeacher Implementation

### ISSUE THREAD

**Issue by Ahmedr275** [marvelai-org/marvel-ai-backend#138]
# AI Assistant Backend Setup: Base Architecture and CoTeacher Implementation

## Overview

This issue focuses on establishing the foundational architecture for AI Assistants on the Marvel platform and implementing the first AI Assistant, **CoTeacher**. The CoTeacher assistant will serve as the prototype and showcase for future assistants to be built upon this base.

The CoTeacher will leverage our existing AI chat framework and incorporate tools, prompts, and actions tailored for classroom management, lesson planning, and administrative support.

---

## Purpose

The maintainers will:
1. **Setup the backend architecture** to allow for seamless creation of new AI assistants in the `/app/assistants` directory.
2. **Implement the CoTeacher assistant** with tools, metadata, and APIs to demonstrate how future assistants can be structured and registered.

---

### Backend Architecture
1. Define the folder structure for AI Assistants under `/app/assistants`.
   - Assistants will be grouped logically under categories, e.g., `classroom_support`.
   - Each assistant will have the following structure:
     - `prompt/` - for prompt configurations.
     - `core.py` - to define the executor logic.
     - `tools.py` - to define AI tools.
     - `metadata.json` - to specify required inputs.

~~2. Register the assistant in `/app/api_config/assistants_config.json`.~~
2. Register the assistant in `/app/assistants/utils/assistants_config.json`.

~~3. Implement the `/assistants` URI endpoint to handle assistant-specific queries.~~
3. Implement the `/assistant-chat` URI endpoint to handle assistant-specific queries.

---

### CoTeacher Assistant
1. **Folder Creation**:
   - Create the `classroom_support/co_teacher` folder under `/app/assistants`.

2. **Files**:
   - **`metadata.json`**: Define inputs for CoTeacher, excluding chat history.
     - Example:
       ```json
       {
         "inputs": [
           {
             "label": "Action",
             "name": "action",
             "type": "text"
           }
         ]
       }
       ```
   - **`tools.py`**:
     - Use LangGraph for CoTeacher tools.
     - ~~Define tools such as `translate`, `summarize`, `rewrite`, and `question_generation`.~~
     - Define reusable actions such as `translate`, `summarize`, `rewrite`, and `question_generation` in `/app/utils/actions_for_assistants`.

   - **`core.py`**:
     - Implement the executor for CoTeacher, reusing the current AI chat approach.
   - **Prompt Folder**:
     - Store the prompt file used for CoTeacher's responses.

3. **Assistant Registration**:
   - Add CoTeacher to `/app/api_config/assistants_config.json`:
     ```json
     {
       "classroom_support": {
         "co_teacher": {
           "path": "assistants.classroom_support.co_teacher.core",
           "metadata_file": "metadata.json"
         }
       }
     }
     ```

4. **Endpoint**:
   - ~~`/assistants`: Ensure CoTeacher-specific queries return correct results.~~
   - `/assistant-chat`: Ensure CoTeacher-specific queries return correct results.

---

## Use Cases
1. **Lesson Planning**:
   - Suggest activities, strategies, and detailed lesson plans.
2. **Classroom Management**:
   - Provide methods to increase student engagement or manage group discussions.
3. **Administrative Support**:
   - Generate emails, student progress reports, and presentations.

---

## Technical Details
- Utilize LangChain/Smith for tools.
- Reuse Kai Chat logic for the executor.
- Maintain flexibility for adding new tools, actions and metadata per assistant.

---

## Acceptance Criteria
- [ ] Folder structure for AI Assistants is established under `/app/assistants`.
- [ ] CoTeacher assistant is implemented in the `/app/assistants/classroom_support/co_teacher` folder.
- [ ] `metadata.json` defines CoTeacher-specific inputs.
- [ ] `tools.py` includes the defined tools: translate, summarize, rewrite, question_generation.
- [ ] `core.py` includes the CoTeacher executor using Kai Chat approach.
- [ ] CoTeacher is registered in `/app/api_config/assistants_config.json`.
- [ ] `/assistants` endpoint returns correct results for CoTeacher-specific queries.
- [ ] Unit tests ensure the following:
  - [ ] Proper functionality of CoTeacher's executor.
  - [ ] Accuracy of tools implemented in `tools.py`.
  - [ ] API returns correct responses for CoTeacher queries.
  - [ ] Inputs defined in `metadata.json` are validated.
- [ ] Code is reviewed and approved.

---

## Resources
- [Figma Prototype](https://www.figma.com/proto/lUJEUgY7DYLCJcx8db3CBK/Marvel---Live?node-id=467-548&node-type=frame&t=2uQ7HmvzI1GYCYzq-1&scaling=min-zoom&content-scaling=fixed&page-id=467%3A539&starting-point-node-id=467%3A1430)

**Comment by AaronSosaRamos** [comment]
Please, check #137 in base of the acceptance criteria @Ahmedr275 @yunusj
