### ISSUE TITLE
ERROR - Quizzify 500

### ISSUE THREAD

**Issue by mikhailocampo** [marvelai-org/marvel-ai-backend#44]
Encountered error that when launching the system via the `uvicorn` command and invoking the Quizzify tool, we see the outputs posted into the terminal as a list of vectors. Assumedly, these vectors are representative of the PDF that was sent.

Command:
`uvicorn main:app --host 0.0.0.0 --port 8000`

**Comment by AaronSosaRamos** [comment]
This issue is solved in the new main branch.
