### ISSUE TITLE
Error in executor: app.features.quizzify.tools.QuizQuestion() argument after ** must be a mapping, not NoneType

### ISSUE THREAD

**Issue by mikhailocampo** [marvelai-org/marvel-ai-backend#48]
![image](https://github.com/radicalxdev/kai-ai-backend/assets/139303992/d62c202f-f420-4f54-ad4a-0adf782df555)
Within the gcloud logs, I found this problem when uploading a file.

My inputs to the kai platform live:
- topic: "convolutional neural networks"
- num_questions: 3
- File: [Convolutional neural network.pdf](https://github.com/user-attachments/files/15916767/Convolutional.neural.network.pdf)

Interestingly, this does not ALWAYS happen. If you can reproduce it

**Comment by AaronSosaRamos** [comment]
@mikhailocampo I've made the PR #49 for solving this issue. Please, check it.

**Comment by AaronSosaRamos** [comment]
This issue is solved in the new v2 version using an util function and few-shot prompting.
