### ISSUE TITLE
HTTPException: 500: Failed to import module from features.quizzify.core: No module named 'features'

### ISSUE THREAD

**Issue by sanithpallerla** [marvelai-org/marvel-ai-backend#50]
Scenario - 1 :

After cloning the changes in the main code base

Code snippet below

![scenario 1](https://github.com/radicalxdev/kai-ai-backend/assets/171053946/6b4f25d4-cc9f-4677-8cc8-59e697e1adc5)

Config snippet below

![Scenario 1 config](https://github.com/radicalxdev/kai-ai-backend/assets/171053946/2d0b21dc-68db-4e1d-9b8b-403180b5532a)

Error snippet below

![Scenario 1 error](https://github.com/radicalxdev/kai-ai-backend/assets/171053946/82a92077-4b36-4f7f-b687-9ff005584d81)

Scenario - 2 :

After changing the config file

Config snippet below

![Scenario 2](https://github.com/radicalxdev/kai-ai-backend/assets/171053946/0937e4a3-6585-4166-8237-d5b89f5909b2)

Error snippet below

![scenario 2 Error](https://github.com/radicalxdev/kai-ai-backend/assets/171053946/6dbd7382-6253-4cb9-997a-0677d1e2afde)

Solution :

Patching the code until a solution is found

![solution](https://github.com/radicalxdev/kai-ai-backend/assets/171053946/dc2696dd-e43e-4b04-b1aa-2c79eaa4548d)

**Comment by mikhailocampo** [comment]
Yes, we introduced the parent module directly in order to allow relative module imports. So when you add `app` to that module, it specified which module path. 

@sanithpallerla Given that you have a solution, can you make a PR for this for me to review the changes and do testing into STAGING? Thanks,

**Comment by AaronSosaRamos** [comment]
@mikhailocampo I have found that the system actually works when I build a Docker Container for it. I think that @sanithpallerla is trying to run the code in his local environment.

**Comment by sanithpallerla** [comment]
@AaronSosaRamos Yes, I completely agree with you. @mikhailocampo I have made the necessary changes. Now it works in Local environment and Docker container and raised a PR from AI-Avengers team's end which includes expedition 7.1 too.
