### ISSUE TITLE
EPIC 6.4 Title & Description Values

### ISSUE THREAD

**Issue by Cosmodocus** [marvelai-org/marvel-ai-backend#62]
Hi, Im software engineer working on EPIC 6.4 Kai Educator Tools History Output. One thing that has been noticeable about the data structure returned by the AI is that there is no value that can be used to properly display either a title or description feature for both the Multiple Choice Assessment and Youtube Flash Cards. Ive had to use some temporary values such as the youtube link for flashcards, but if this could be solved, this would greatly enhance the UI for this expedition.

**Comment by AaronSosaRamos** [comment]
Hi @Cosmodocus. I've made a PR for solving your request. PR #63

**Comment by Cosmodocus** [comment]
Glad to hear! Looking forward to it :)
